### ISSUE TITLE
Implement universal curve interface

### ISSUE THREAD

**Issue by collinc97** [gnosis/dkg#10]
Currently, there are separate branches for each curve. There are many curves out there, so we should re-design to accommodate them without multiple branches.

**Comment by cag** [comment]
For reference, curves are:

* elliptic.Curves that can be found [here](https://golang.org/pkg/crypto/elliptic/).
* even more elliptic curves which can be found [here](https://github.com/ethereum/go-ethereum/tree/master/crypto/secp256k1)
* Pairing friendly curves which can be found [here](https://godoc.org/golang.org/x/crypto/bn256)
* Any ol crypto thing that is isomorphic to a finite vector field

**Comment by cag** [comment]
We're using [kyber Group interface](https://godoc.org/github.com/dedis/kyber#Group) for this purpose.
