### ISSUE TITLE
Research Broadcast Messaging Options

### ISSUE THREAD

**Issue by cag** [gnosis/dkg#2]
Some existing options:

* ZeroMQ
* IPFS
* libp2p (underlies IPFS)
* devp2p (underlies Ethereum)

Some requirements:

* Nodes have to be able to get all info they need even if they join late or their connection is spotty or something.

**Comment by collinc97** [comment]
Current research at https://hackmd.io/_tL04Jv_QcWnr4ab22kJ8w?

**Comment by collinc97** [comment]
Network Requirements as of 7-27-18:
* Room "chat" (ideally supports binary messages) functionality
* Room history functionality
* private messages covered by tying public key to identity
* broadcast messages can be signed
